# Generated by Django 5.2 on 2025-05-03 18:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Le numéro de téléphone doit être au format international (ex. : +1234567890).')], verbose_name='Téléphone')),
                ('address', models.CharField(max_length=60, verbose_name='Adresse')),
                ('sex', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1, verbose_name='Sexe')),
                ('city', models.CharField(max_length=30, verbose_name='Ville')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de la facture')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('invoice_type', models.CharField(choices=[('R', 'Reçu'), ('P', 'Facture proforma'), ('F', 'Facture')], max_length=1, verbose_name='Type de facture')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total')),
                ('comments', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaires')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='facture_app.customer', verbose_name='Client')),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='PharmacyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Produit pharmaceutique',
                'verbose_name_plural': 'Produits pharmaceutiques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='La quantité doit être positive.')], verbose_name='Quantité')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='facture_app.invoice', verbose_name='Facture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='facture_app.pharmacyproduct', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email', 'name'], name='facture_app_email_922e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date_time', 'customer'], name='facture_app_invoice_cc611d_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyproduct',
            index=models.Index(fields=['name'], name='facture_app_name_2ce76f_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['invoice', 'product'], name='facture_app_invoice_a84766_idx'),
        ),
    ]
